-- =============================================================================
-- Migration: 007_placements.sql
-- Description: Core placement records, phase tracking, and tripartite agreements
--              (CA0355). This is the central entity linking all other tables.
-- Platform: EDUK8U Work Placement Intelligence Platform
-- Author: DB Schema Agent
-- Created: 2026-06-04
-- Depends on: 001_tenancy_auth.sql, 003_workflow_engine.sql,
--             004_host_facilities.sql, 005_supervisors.sql, 006_students.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
CREATE TYPE placement_status AS ENUM (
  'setup',
  'active',
  'monitoring',
  'on_hold',
  'completed',
  'cancelled',
  'failed'
);

CREATE TYPE risk_level AS ENUM (
  'none',
  'low',
  'medium',
  'high',
  'critical'
);

CREATE TYPE phase_status AS ENUM (
  'pending',
  'in_progress',
  'completed',
  'skipped',
  'blocked'
);

CREATE TYPE tripartite_status AS ENUM (
  'draft',
  'pending_signatures',
  'student_signed',
  'supervisor_signed',
  'fully_signed',
  'expired'
);

COMMENT ON TYPE placement_status IS
  'Lifecycle states for a work placement: setup → active → monitoring → completed';
COMMENT ON TYPE risk_level IS
  'Risk severity classification for placements flagged by compliance engine';
COMMENT ON TYPE phase_status IS
  'Progress state for an individual workflow phase within a placement';
COMMENT ON TYPE tripartite_status IS
  'Signature collection progress for the CA0355 tripartite agreement';

-- ---------------------------------------------------------------------------
-- Placements
-- The central entity — one row per student-placement-host assignment
-- ---------------------------------------------------------------------------
CREATE TABLE placements (
  id                     UUID              PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id              UUID              NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  placement_reference    VARCHAR(50)       UNIQUE,
  student_id             UUID              NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  host_facility_id       UUID              NOT NULL REFERENCES host_facilities(id),
  supervisor_id          UUID              REFERENCES supervisors(id),
  trainer_id             UUID              REFERENCES users(id),
  workflow_definition_id UUID              REFERENCES workflow_definitions(id),
  course_code            VARCHAR(50)       DEFAULT 'CHC33021',
  total_hours_required   INTEGER           DEFAULT 120,
  hours_completed        DECIMAL(6,2)      DEFAULT 0,
  hours_verified         DECIMAL(6,2)      DEFAULT 0,
  planned_start_date     DATE,
  actual_start_date      DATE,
  planned_end_date       DATE,
  actual_end_date        DATE,
  current_phase          VARCHAR(100)      DEFAULT 'host_establishment',
  status                 placement_status  DEFAULT 'setup',
  risk_level             risk_level        DEFAULT 'none',
  is_at_risk             BOOLEAN           DEFAULT false,
  risk_reason            TEXT,
  completion_percentage  DECIMAL(5,2)      DEFAULT 0,
  audit_readiness_score  DECIMAL(5,2)      DEFAULT 0,
  last_monitoring_visit  DATE,
  notes                  TEXT,
  metadata               JSONB             DEFAULT '{}',
  created_by             UUID              REFERENCES users(id),
  created_at             TIMESTAMPTZ       DEFAULT NOW(),
  updated_at             TIMESTAMPTZ       DEFAULT NOW(),
  CONSTRAINT chk_hours_completed CHECK (hours_completed >= 0),
  CONSTRAINT chk_hours_verified CHECK (hours_verified >= 0 AND hours_verified <= hours_completed),
  CONSTRAINT chk_completion_pct CHECK (completion_percentage BETWEEN 0 AND 100),
  CONSTRAINT chk_audit_score CHECK (audit_readiness_score BETWEEN 0 AND 100),
  CONSTRAINT chk_placement_dates CHECK (
    planned_start_date IS NULL OR planned_end_date IS NULL
    OR planned_start_date <= planned_end_date
  )
);

COMMENT ON TABLE placements IS
  'The central placement record linking a student, host facility, supervisor, and trainer. '
  'All compliance checks, hours, evidence, and sign-offs hang off this entity.';
COMMENT ON COLUMN placements.placement_reference IS
  'Human-readable reference, e.g. PL-2024-00123. Generated by application on creation.';
COMMENT ON COLUMN placements.hours_completed IS
  'Denormalised sum of placement_hours.hours_claimed for verified+pending entries';
COMMENT ON COLUMN placements.hours_verified IS
  'Denormalised sum of placement_hours.hours_claimed for supervisor-verified entries only';
COMMENT ON COLUMN placements.current_phase IS
  'step_key of the active workflow step — drives UI progress indicators';
COMMENT ON COLUMN placements.audit_readiness_score IS
  'Percentage (0–100) computed by compliance engine; reflects ASQA audit readiness';
COMMENT ON COLUMN placements.is_at_risk IS
  'True when active risk flags exist at medium severity or above';

-- ---------------------------------------------------------------------------
-- Placement Phase Tracking
-- Mirrors workflow_steps for each specific placement — tracks actual progress
-- ---------------------------------------------------------------------------
CREATE TABLE placement_phases (
  id            UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id     UUID          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  placement_id  UUID          NOT NULL REFERENCES placements(id) ON DELETE CASCADE,
  phase_key     VARCHAR(100)  NOT NULL,
  phase_name    VARCHAR(255)  NOT NULL,
  phase_order   INTEGER       NOT NULL,
  status        phase_status  DEFAULT 'pending',
  started_at    TIMESTAMPTZ,
  completed_at  TIMESTAMPTZ,
  completed_by  UUID          REFERENCES users(id),
  blockers      JSONB         DEFAULT '[]',
  notes         TEXT,
  created_at    TIMESTAMPTZ   DEFAULT NOW(),
  UNIQUE(placement_id, phase_key)
);

COMMENT ON TABLE placement_phases IS
  'Per-placement instantiation of workflow steps. Records actual start/complete '
  'timestamps and any blockers preventing phase advancement.';
COMMENT ON COLUMN placement_phases.blockers IS
  'Array of {blocker_type, description, created_at} objects — cleared when phase completes';

-- ---------------------------------------------------------------------------
-- CA 0355: Tripartite Agreement
-- Three-way agreement between student, host supervisor, and RTO trainer
-- Must be fully_signed before placement active hours can be logged
-- ---------------------------------------------------------------------------
CREATE TABLE tripartite_agreements (
  id                        UUID               PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id                 UUID               NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  placement_id              UUID               NOT NULL REFERENCES placements(id) ON DELETE CASCADE,
  form_code                 VARCHAR(20)        DEFAULT 'CA0355',
  agreement_number          VARCHAR(50)        UNIQUE,
  agreement_date            DATE,
  placement_start_date      DATE,
  placement_end_date        DATE,
  total_hours               INTEGER            DEFAULT 120,
  placement_location        TEXT,
  learning_objectives       TEXT,
  assessment_requirements   TEXT,
  whs_responsibilities      TEXT,
  special_conditions        TEXT,
  status                    tripartite_status  DEFAULT 'draft',
  -- Student signature block
  student_name              VARCHAR(255),
  student_signed_at         TIMESTAMPTZ,
  student_signature_data    TEXT,
  student_signed_ip         INET,
  -- Supervisor signature block
  supervisor_name           VARCHAR(255),
  supervisor_signed_at      TIMESTAMPTZ,
  supervisor_signature_data TEXT,
  supervisor_signed_ip      INET,
  -- Trainer/RTO signature block
  trainer_name              VARCHAR(255),
  trainer_signed_at         TIMESTAMPTZ,
  trainer_signature_data    TEXT,
  trainer_signed_ip         INET,
  document_id               UUID,
  created_by                UUID               REFERENCES users(id),
  created_at                TIMESTAMPTZ        DEFAULT NOW(),
  updated_at                TIMESTAMPTZ        DEFAULT NOW(),
  CONSTRAINT chk_tripartite_dates CHECK (
    placement_start_date IS NULL OR placement_end_date IS NULL
    OR placement_start_date <= placement_end_date
  )
);

COMMENT ON TABLE tripartite_agreements IS
  'CA0355 — Three-party agreement between student, supervisor, and trainer/RTO. '
  'All three signatures required before status becomes "fully_signed" and hours logging is enabled.';
COMMENT ON COLUMN tripartite_agreements.student_signature_data IS
  'Base64-encoded PNG/SVG of the student''s electronic signature';
COMMENT ON COLUMN tripartite_agreements.supervisor_signature_data IS
  'Base64-encoded PNG/SVG of the supervisor''s electronic signature';
COMMENT ON COLUMN tripartite_agreements.trainer_signature_data IS
  'Base64-encoded PNG/SVG of the trainer/RTO representative''s electronic signature';

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX idx_placements_tenant     ON placements(tenant_id);
CREATE INDEX idx_placements_student    ON placements(student_id);
CREATE INDEX idx_placements_host       ON placements(host_facility_id);
CREATE INDEX idx_placements_supervisor ON placements(supervisor_id);
CREATE INDEX idx_placements_trainer    ON placements(trainer_id);
CREATE INDEX idx_placements_status     ON placements(status);
CREATE INDEX idx_placements_risk       ON placements(risk_level, is_at_risk);
CREATE INDEX idx_placements_active     ON placements(tenant_id, status)
  WHERE status IN ('setup', 'active', 'monitoring', 'on_hold');

CREATE INDEX idx_placement_phases_placement ON placement_phases(placement_id);
CREATE INDEX idx_placement_phases_status    ON placement_phases(placement_id, status);

CREATE INDEX idx_tripartite_placement ON tripartite_agreements(placement_id);
CREATE INDEX idx_tripartite_status    ON tripartite_agreements(status);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------
CREATE TRIGGER update_placements_updated_at
  BEFORE UPDATE ON placements
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tripartite_updated_at
  BEFORE UPDATE ON tripartite_agreements
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
