-- =============================================================================
-- Migration: 010_compliance_risk.sql
-- Description: Risk flag management, compliance snapshots, and feedback records
--              Powers the ASQA audit readiness engine
-- Platform: EDUK8U Work Placement Intelligence Platform
-- Author: DB Schema Agent
-- Created: 2026-06-04
-- Depends on: 001_tenancy_auth.sql, 007_placements.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
CREATE TYPE flag_severity AS ENUM (
  'low',
  'medium',
  'high',
  'critical'
);

CREATE TYPE flag_status AS ENUM (
  'active',
  'acknowledged',
  'resolved',
  'false_positive'
);

COMMENT ON TYPE flag_severity IS
  'Risk severity classification; critical flags trigger immediate escalation';
COMMENT ON TYPE flag_status IS
  'Lifecycle state for a risk flag raised against a placement';

-- ---------------------------------------------------------------------------
-- Placement Risk Flags
-- Auto-generated or manually raised alerts indicating compliance gaps.
-- Drives the risk_level field on the parent placement record.
-- ---------------------------------------------------------------------------
CREATE TABLE placement_risk_flags (
  id                UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id         UUID          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  placement_id      UUID          NOT NULL REFERENCES placements(id) ON DELETE CASCADE,
  flag_type         VARCHAR(100)  NOT NULL,
  severity          flag_severity NOT NULL,
  title             VARCHAR(255)  NOT NULL,
  description       TEXT          NOT NULL,
  auto_generated    BOOLEAN       DEFAULT true,
  status            flag_status   DEFAULT 'active',
  raised_at         TIMESTAMPTZ   DEFAULT NOW(),
  raised_by         UUID          REFERENCES users(id),
  acknowledged_at   TIMESTAMPTZ,
  acknowledged_by   UUID          REFERENCES users(id),
  resolved_at       TIMESTAMPTZ,
  resolved_by       UUID          REFERENCES users(id),
  resolution_notes  TEXT,
  escalated_at      TIMESTAMPTZ,
  escalated_to      UUID          REFERENCES users(id),
  metadata          JSONB         DEFAULT '{}',
  created_at        TIMESTAMPTZ   DEFAULT NOW()
);

COMMENT ON TABLE placement_risk_flags IS
  'Risk and compliance flags raised against placements. Auto-generated by the '
  'compliance engine on schedule, or manually raised by trainers and admins.';
COMMENT ON COLUMN placement_risk_flags.flag_type IS
  'Machine-readable type key: "hours_behind", "missing_signature", '
  '"overdue_monitoring", "expired_insurance", "supervisor_unverified", etc.';
COMMENT ON COLUMN placement_risk_flags.auto_generated IS
  'True when raised by automated compliance engine; false when raised manually';
COMMENT ON COLUMN placement_risk_flags.metadata IS
  'Additional context: threshold values, expected vs actual counts, rule version, etc.';

-- ---------------------------------------------------------------------------
-- Compliance Snapshots
-- Point-in-time compliance scores and checklist states for each placement.
-- Generated on demand and at scheduled intervals for audit reports.
-- The 8 boolean fields represent the ASQA audit checklist required items.
-- ---------------------------------------------------------------------------
CREATE TABLE compliance_snapshots (
  id                          UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id                   UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  placement_id                UUID         NOT NULL REFERENCES placements(id) ON DELETE CASCADE,
  snapshot_date               TIMESTAMPTZ  DEFAULT NOW(),
  overall_compliance_score    DECIMAL(5,2) DEFAULT 0,
  audit_readiness_score       DECIMAL(5,2) DEFAULT 0,
  hours_compliance_score      DECIMAL(5,2) DEFAULT 0,
  documents_compliance_score  DECIMAL(5,2) DEFAULT 0,
  signatures_compliance_score DECIMAL(5,2) DEFAULT 0,
  -- 8-point ASQA audit readiness checklist
  host_approved               BOOLEAN      DEFAULT false,
  supervisor_verified         BOOLEAN      DEFAULT false,
  learner_ready               BOOLEAN      DEFAULT false,
  agreement_signed            BOOLEAN      DEFAULT false,
  hours_completed             BOOLEAN      DEFAULT false,
  evidence_available          BOOLEAN      DEFAULT false,
  monitoring_completed        BOOLEAN      DEFAULT false,
  final_signoff_complete      BOOLEAN      DEFAULT false,
  -- Gap analysis detail
  missing_documents           JSONB        DEFAULT '[]',
  missing_signatures          JSONB        DEFAULT '[]',
  missing_hours               DECIMAL(6,2) DEFAULT 0,
  missing_evidence_count      INTEGER      DEFAULT 0,
  missing_monitoring_visits   INTEGER      DEFAULT 0,
  risk_flags_count            INTEGER      DEFAULT 0,
  risk_flags_critical         INTEGER      DEFAULT 0,
  -- Full machine-readable checklist
  full_checklist              JSONB        DEFAULT '{}',
  generated_by                UUID         REFERENCES users(id),
  created_at                  TIMESTAMPTZ  DEFAULT NOW(),
  CONSTRAINT chk_scores CHECK (
    overall_compliance_score BETWEEN 0 AND 100
    AND audit_readiness_score BETWEEN 0 AND 100
    AND hours_compliance_score BETWEEN 0 AND 100
    AND documents_compliance_score BETWEEN 0 AND 100
    AND signatures_compliance_score BETWEEN 0 AND 100
  )
);

COMMENT ON TABLE compliance_snapshots IS
  'Immutable compliance scoring snapshots. Each row is a complete compliance '
  'assessment at a point in time, enabling trend analysis and audit trails.';
COMMENT ON COLUMN compliance_snapshots.overall_compliance_score IS
  'Weighted aggregate of all sub-scores (0–100); drives the placement dashboard gauge';
COMMENT ON COLUMN compliance_snapshots.audit_readiness_score IS
  'Fraction of ASQA 8-point checklist items satisfied, expressed as 0–100';
COMMENT ON COLUMN compliance_snapshots.missing_documents IS
  'Array of {form_code, label, entity_type, entity_id} for outstanding required docs';
COMMENT ON COLUMN compliance_snapshots.full_checklist IS
  'Complete {item_key: {label, passed, detail}} map used to render the audit checklist';

-- ---------------------------------------------------------------------------
-- Feedback Records
-- Post-placement feedback from students, supervisors, and trainers
-- Used for Continuous Improvement (CI) reporting required by ASQA
-- ---------------------------------------------------------------------------
CREATE TABLE feedback_records (
  id                   UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id            UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  placement_id         UUID         NOT NULL REFERENCES placements(id) ON DELETE CASCADE,
  feedback_type        VARCHAR(50)  NOT NULL,
  submitted_by         UUID         REFERENCES users(id),
  submitter_role       VARCHAR(50),
  overall_rating       INTEGER      CHECK (overall_rating BETWEEN 1 AND 5),
  would_recommend      BOOLEAN,
  responses            JSONB        DEFAULT '{}',
  strengths            TEXT,
  areas_for_improvement TEXT,
  is_anonymous         BOOLEAN      DEFAULT false,
  created_at           TIMESTAMPTZ  DEFAULT NOW()
);

COMMENT ON TABLE feedback_records IS
  'Post-placement feedback surveys. Supports ASQA Continuous Improvement reporting '
  'obligations under Standards for RTOs 2015 Clause 2.2.';
COMMENT ON COLUMN feedback_records.feedback_type IS
  'Survey type: "student_post_placement" | "supervisor_post_placement" | "trainer_review"';
COMMENT ON COLUMN feedback_records.responses IS
  'JSON map of {question_key: answer_value} for all survey questions';

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX idx_risk_flags_placement  ON placement_risk_flags(placement_id);
CREATE INDEX idx_risk_flags_status     ON placement_risk_flags(status);
CREATE INDEX idx_risk_flags_severity   ON placement_risk_flags(severity);
CREATE INDEX idx_risk_flags_active     ON placement_risk_flags(tenant_id, status)
  WHERE status = 'active';
CREATE INDEX idx_risk_flags_tenant     ON placement_risk_flags(tenant_id);

CREATE INDEX idx_compliance_snapshots_placement ON compliance_snapshots(placement_id);
CREATE INDEX idx_compliance_snapshots_date      ON compliance_snapshots(snapshot_date DESC);
CREATE INDEX idx_compliance_snapshots_tenant    ON compliance_snapshots(tenant_id);

CREATE INDEX idx_feedback_placement ON feedback_records(placement_id);
CREATE INDEX idx_feedback_type      ON feedback_records(feedback_type);
