-- =============================================================================
-- Migration: 012_seed_data.sql
-- Description: Billing scaffold tables, CHC33021 workflow definition with all
--              16 phases, notification templates, demo tenant, and super admin user
-- Platform: EDUK8U Work Placement Intelligence Platform
-- Author: DB Schema Agent
-- Created: 2026-06-04
-- Depends on: All previous migrations (001–011)
-- =============================================================================

-- =============================================================================
-- PART 1: BILLING SCAFFOLD
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Subscriptions
-- One active subscription per tenant; historical records are retained
-- ---------------------------------------------------------------------------
CREATE TABLE subscriptions (
  id                     UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id              UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  plan_name              VARCHAR(50)  NOT NULL,
  status                 VARCHAR(50)  DEFAULT 'active'
                                      CHECK (status IN ('active', 'trialling', 'past_due', 'cancelled', 'unpaid', 'paused')),
  billing_cycle          VARCHAR(20)  DEFAULT 'monthly'
                                      CHECK (billing_cycle IN ('monthly', 'annual')),
  amount                 DECIMAL(10,2),
  currency               VARCHAR(3)   DEFAULT 'AUD',
  max_students           INTEGER,
  max_placements         INTEGER,
  current_period_start   TIMESTAMPTZ,
  current_period_end     TIMESTAMPTZ,
  stripe_subscription_id VARCHAR(255),
  stripe_customer_id     VARCHAR(255),
  cancelled_at           TIMESTAMPTZ,
  created_at             TIMESTAMPTZ  DEFAULT NOW(),
  updated_at             TIMESTAMPTZ  DEFAULT NOW(),
  CONSTRAINT chk_amount CHECK (amount IS NULL OR amount >= 0),
  CONSTRAINT chk_max_students CHECK (max_students IS NULL OR max_students > 0),
  CONSTRAINT chk_period_dates CHECK (
    current_period_start IS NULL OR current_period_end IS NULL
    OR current_period_start < current_period_end
  )
);

COMMENT ON TABLE subscriptions IS
  'Billing subscription records per tenant. Integrates with Stripe; '
  'stripe_subscription_id and stripe_customer_id are the external references.';
COMMENT ON COLUMN subscriptions.max_students IS
  'Plan-level student enrolment cap; NULL = unlimited (enterprise)';
COMMENT ON COLUMN subscriptions.max_placements IS
  'Plan-level concurrent placement cap; NULL = unlimited (enterprise)';

CREATE INDEX idx_subscriptions_tenant        ON subscriptions(tenant_id);
CREATE INDEX idx_subscriptions_stripe_sub    ON subscriptions(stripe_subscription_id)
  WHERE stripe_subscription_id IS NOT NULL;
CREATE INDEX idx_subscriptions_stripe_cust   ON subscriptions(stripe_customer_id)
  WHERE stripe_customer_id IS NOT NULL;
CREATE INDEX idx_subscriptions_status        ON subscriptions(status);

CREATE TRIGGER update_subscriptions_updated_at
  BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- Invoices
-- Generated by billing engine; can be reconciled against Stripe invoices
-- ---------------------------------------------------------------------------
CREATE TABLE invoices (
  id               UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id        UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  subscription_id  UUID         REFERENCES subscriptions(id),
  invoice_number   VARCHAR(50)  UNIQUE,
  amount           DECIMAL(10,2) NOT NULL,
  currency         VARCHAR(3)   DEFAULT 'AUD',
  status           VARCHAR(50)  DEFAULT 'draft'
                                CHECK (status IN ('draft', 'open', 'paid', 'void', 'uncollectible')),
  due_date         DATE,
  paid_at          TIMESTAMPTZ,
  invoice_pdf_url  TEXT,
  line_items       JSONB        DEFAULT '[]',
  created_at       TIMESTAMPTZ  DEFAULT NOW(),
  CONSTRAINT chk_invoice_amount CHECK (amount >= 0)
);

COMMENT ON TABLE invoices IS
  'Invoice records for tenant billing. Synced with Stripe invoice objects.';
COMMENT ON COLUMN invoices.line_items IS
  'Array of {description, quantity, unit_price, amount} line item objects';

CREATE INDEX idx_invoices_tenant     ON invoices(tenant_id);
CREATE INDEX idx_invoices_status     ON invoices(status);
CREATE INDEX idx_invoices_due_date   ON invoices(due_date) WHERE due_date IS NOT NULL;

-- =============================================================================
-- PART 2: DEMO TENANT — ICQA
-- =============================================================================

INSERT INTO tenants (
  id,
  name,
  slug,
  abn,
  rto_code,
  subscription_tier,
  is_active,
  contact_email,
  contact_phone,
  address,
  settings
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  'ICQA Institute',
  'icqa',
  '12345678901',
  'RTO-12345',
  'enterprise',
  true,
  'admin@icqa.edu.au',
  '+61 2 9000 0000',
  'Level 5, 123 Education Street, Sydney NSW 2000',
  '{
    "timezone": "Australia/Sydney",
    "date_format": "DD/MM/YYYY",
    "placement_hours_required": 120,
    "course_code": "CHC33021",
    "enable_e_signatures": true,
    "enable_supervisor_portal": true,
    "enable_student_portal": true,
    "asqa_audit_mode": true
  }'::jsonb
);

-- =============================================================================
-- PART 3: SUPER ADMIN USER
-- =============================================================================
-- IMPORTANT: The password hash below is a bcrypt hash of 'Admin@ICQA2024!'
-- with cost factor 12.
-- YOU MUST REGENERATE THIS HASH before production deployment using:
--   node -e "const bcrypt = require('bcrypt'); bcrypt.hash('YourNewPassword', 12).then(console.log);"
-- or equivalent. Do NOT deploy with this placeholder hash in production.
-- ---------------------------------------------------------------------------

INSERT INTO users (
  id,
  tenant_id,
  email,
  password_hash,
  first_name,
  last_name,
  role,
  is_active,
  is_email_verified,
  email_verified_at
) VALUES (
  '00000000-0000-0000-0000-000000000002',
  NULL,
  'superadmin@eduk8u.com',
  -- bcrypt hash of 'Admin@ICQA2024!' at cost 12
  -- REPLACE THIS WITH A FRESHLY GENERATED HASH BEFORE PRODUCTION DEPLOYMENT
  '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMqJqhcanFueVymbm3Zl9sn/.',
  'Super',
  'Admin',
  'super_admin',
  true,
  true,
  NOW()
);

-- Insert ICQA college admin
INSERT INTO users (
  id,
  tenant_id,
  email,
  password_hash,
  first_name,
  last_name,
  role,
  is_active,
  is_email_verified,
  email_verified_at
) VALUES (
  '00000000-0000-0000-0000-000000000003',
  '00000000-0000-0000-0000-000000000001',
  'admin@icqa.edu.au',
  -- bcrypt hash of 'Admin@ICQA2024!' at cost 12
  -- REPLACE THIS WITH A FRESHLY GENERATED HASH BEFORE PRODUCTION DEPLOYMENT
  '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMqJqhcanFueVymbm3Zl9sn/.',
  'ICQA',
  'Administrator',
  'college_admin',
  true,
  true,
  NOW()
);

-- =============================================================================
-- PART 4: CHC33021 WORKFLOW DEFINITION (Certificate III in Individual Support)
-- 16 phases covering the complete placement lifecycle
-- =============================================================================

INSERT INTO workflow_definitions (
  id,
  tenant_id,
  name,
  course_code,
  description,
  total_hours_required,
  version,
  is_active,
  config,
  created_by
) VALUES (
  '00000000-0000-0000-0000-000000000010',
  '00000000-0000-0000-0000-000000000001',
  'CHC33021 Work Placement Workflow',
  'CHC33021',
  'Complete work placement management workflow for Certificate III in Individual Support. '
  'Covers all 16 phases from host establishment through to records retention. '
  'Aligns with ASQA Standards for RTOs 2015 and CHC Community Services Training Package.',
  120,
  1,
  true,
  '{
    "allow_concurrent_phases": false,
    "require_tripartite_before_hours": true,
    "auto_flag_overdue_hours": true,
    "overdue_hours_threshold_days": 14,
    "monitoring_visit_frequency_weeks": 4,
    "require_supervisor_signature_per_week": true,
    "compliance_engine_enabled": true,
    "notify_trainer_on_risk": true,
    "notify_admin_on_critical_risk": true,
    "documents_required_before_commencement": [
      "CA0393", "CA0316", "CA0395", "CA0401", "CA0398", "LS0013", "CA0355"
    ]
  }'::jsonb,
  '00000000-0000-0000-0000-000000000003'
);

-- ---------------------------------------------------------------------------
-- Workflow Steps (16 phases)
-- ---------------------------------------------------------------------------
INSERT INTO workflow_steps
  (workflow_definition_id, step_order, step_key, step_name, step_description,
   is_required, required_documents, required_signatures, required_forms, config)
VALUES

-- Phase 1: Host Establishment
(
  '00000000-0000-0000-0000-000000000010', 1, 'host_establishment',
  'Host Facility Setup',
  'Identify and register the host facility. Capture all facility details, ABN, '
  'contact information, and primary supervisor. Verify the facility type is appropriate '
  'for CHC33021 placement requirements.',
  true,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{"sla_hours": 48, "notify_on_complete": ["trainer", "admin"]}'::jsonb
),

-- Phase 2: Host Suitability Check
(
  '00000000-0000-0000-0000-000000000010', 2, 'host_suitability_check',
  'CA0393 Suitability Check',
  'Complete the CA0393 Host Facility Suitability Checklist. Assess physical environment, '
  'supervision capacity, equipment, WHS compliance, and policies. Minimum scores required '
  'in all dimensions before proceeding.',
  true,
  '[{"form_code": "CA0393", "label": "Host Facility Suitability Checklist", "is_mandatory": true}]'::jsonb,
  '[{"signer_role": "trainer", "label": "Trainer Assessment Sign-off"}]'::jsonb,
  '["CA0393"]'::jsonb,
  '{"sla_hours": 72, "min_score_required": 3, "notify_on_complete": ["trainer", "admin"]}'::jsonb
),

-- Phase 3: Insurance Verification
(
  '00000000-0000-0000-0000-000000000010', 3, 'insurance_verification',
  'Insurance Verification',
  'Collect and verify current public liability insurance documentation from the host facility. '
  'Minimum coverage of $10M AUD required. Record policy details and expiry dates for '
  'automated renewal alerts.',
  true,
  '[{"form_code": "INS001", "label": "Public Liability Insurance Certificate", "is_mandatory": true}]'::jsonb,
  '[{"signer_role": "college_admin", "label": "Insurance Verification Sign-off"}]'::jsonb,
  '[]'::jsonb,
  '{
    "sla_hours": 48,
    "minimum_coverage_aud": 10000000,
    "alert_before_expiry_days": 30,
    "notify_on_complete": ["trainer"]
  }'::jsonb
),

-- Phase 4: Workplace Agreement
(
  '00000000-0000-0000-0000-000000000010', 4, 'workplace_agreement',
  'CA0316 Workplace Agreement',
  'Prepare, send, and collect fully signed CA0316 Workplace Agreement between the RTO '
  'and the host organisation. Both parties must sign before placement can proceed. '
  'Agreement defines responsibilities, WHS obligations, and valid dates.',
  true,
  '[{"form_code": "CA0316", "label": "Workplace Agreement", "is_mandatory": true}]'::jsonb,
  '[
    {"signer_role": "host_manager", "label": "Host Organisation Signature"},
    {"signer_role": "college_admin", "label": "RTO Authorised Signatory"}
  ]'::jsonb,
  '["CA0316"]'::jsonb,
  '{
    "sla_hours": 120,
    "agreement_valid_years": 3,
    "auto_generate_agreement_number": true,
    "notify_on_complete": ["trainer", "admin", "host_manager"]
  }'::jsonb
),

-- Phase 5: Supervisor Assignment
(
  '00000000-0000-0000-0000-000000000010', 5, 'supervisor_assignment',
  'Supervisor Assignment',
  'Identify and assign a qualified supervisor at the host facility for this student. '
  'Confirm the supervisor holds appropriate qualifications for CHC33021 supervision '
  'and is willing to undertake the role. Create supervisor profile if not existing.',
  true,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{"sla_hours": 24, "notify_supervisor": true, "notify_on_complete": ["trainer"]}'::jsonb
),

-- Phase 6: Supervisor Verification
(
  '00000000-0000-0000-0000-000000000010', 6, 'supervisor_verification',
  'CA0395 Supervisor Verification',
  'Collect and verify supervisor qualifications using CA0395. Confirm relevant industry '
  'experience and current registration where applicable (e.g. AHPRA for nursing). '
  'Supervisor must be assessed as suitable before briefing.',
  true,
  '[{"form_code": "CA0395", "label": "Supervisor Qualification Verification", "is_mandatory": true}]'::jsonb,
  '[{"signer_role": "trainer", "label": "Trainer Verification Sign-off"}]'::jsonb,
  '["CA0395"]'::jsonb,
  '{
    "sla_hours": 72,
    "notify_on_complete": ["trainer", "admin"],
    "notify_supervisor_on_approval": true
  }'::jsonb
),

-- Phase 7: Supervisor Briefing
(
  '00000000-0000-0000-0000-000000000010', 7, 'supervisor_briefing',
  'CA0401 Supervisor Briefing',
  'Conduct supervisor briefing using CA0401 Supervisor Guide. Cover all obligations, '
  'student assessment requirements, competency sign-off procedures, WHS responsibilities, '
  'emergency procedures, and communication expectations. Obtain acknowledgement.',
  true,
  '[{"form_code": "CA0401", "label": "Supervisor Guide & Briefing Record", "is_mandatory": true}]'::jsonb,
  '[{"signer_role": "supervisor", "label": "Supervisor Acknowledgement"}]'::jsonb,
  '["CA0401"]'::jsonb,
  '{
    "sla_hours": 48,
    "briefing_topics": [
      "supervisor_obligations",
      "assessment_requirements",
      "competency_signoff_process",
      "hour_log_verification",
      "emergency_procedures",
      "whs_requirements",
      "communication_protocols",
      "student_support_processes"
    ],
    "notify_on_complete": ["trainer"]
  }'::jsonb
),

-- Phase 8: Learner Readiness
(
  '00000000-0000-0000-0000-000000000010', 8, 'learner_readiness',
  'CA0398 Learner Readiness',
  'Complete CA0398 Pre-Placement Learner Readiness Assessment. Verify police check '
  '(within 3 years), WWCC (current), First Aid certification (within 3 years), and '
  'all mandatory prerequisite training. Student must be assessed as "ready" to proceed.',
  true,
  '[
    {"form_code": "CA0398", "label": "Pre-Placement Readiness Assessment", "is_mandatory": true},
    {"form_code": "POLICE", "label": "National Police Check", "is_mandatory": true},
    {"form_code": "WWCC", "label": "Working With Children Check", "is_mandatory": true},
    {"form_code": "FIRSTAID", "label": "First Aid Certificate", "is_mandatory": true}
  ]'::jsonb,
  '[{"signer_role": "trainer", "label": "Trainer Readiness Sign-off"}]'::jsonb,
  '["CA0398"]'::jsonb,
  '{
    "sla_hours": 48,
    "police_check_max_age_years": 3,
    "wwcc_must_be_current": true,
    "first_aid_max_age_years": 3,
    "notify_on_complete": ["trainer", "student"]
  }'::jsonb
),

-- Phase 9: Learner Information Pack
(
  '00000000-0000-0000-0000-000000000010', 9, 'learner_info_pack',
  'LS0013 Info Pack',
  'Issue and obtain acknowledgement for LS0013 Learner Information Pack. '
  'Pack must include placement schedule, assessment requirements, contact details, '
  'emergency procedures, WHS information, and student support services.',
  true,
  '[{"form_code": "LS0013", "label": "Learner Information Pack", "is_mandatory": true}]'::jsonb,
  '[{"signer_role": "student", "label": "Student Acknowledgement"}]'::jsonb,
  '["LS0013"]'::jsonb,
  '{"sla_hours": 24, "notify_on_complete": ["trainer"]}'::jsonb
),

-- Phase 10: Tripartite Agreement
(
  '00000000-0000-0000-0000-000000000010', 10, 'tripartite_agreement',
  'CA0355 Tripartite Agreement',
  'Prepare and collect all three signatures on CA0355 Tripartite Placement Agreement. '
  'Student, supervisor, and trainer must all sign before the student can commence '
  'logging hours. Agreement specifies dates, hours, objectives, and WHS responsibilities.',
  true,
  '[{"form_code": "CA0355", "label": "Tripartite Placement Agreement", "is_mandatory": true}]'::jsonb,
  '[
    {"signer_role": "student", "label": "Student Signature"},
    {"signer_role": "supervisor", "label": "Supervisor Signature"},
    {"signer_role": "trainer", "label": "Trainer/RTO Signature"}
  ]'::jsonb,
  '["CA0355"]'::jsonb,
  '{
    "sla_hours": 72,
    "all_three_signatures_required": true,
    "enable_hours_logging_after_completion": true,
    "notify_on_complete": ["trainer", "student", "supervisor"]
  }'::jsonb
),

-- Phase 11: Placement Commencement
(
  '00000000-0000-0000-0000-000000000010', 11, 'placement_commencement',
  'Placement Start',
  'Student commences placement. Record actual start date. Confirm student has arrived '
  'at the facility. Send commencement notifications. Begin monitoring clock. '
  'Placement status transitions to "active" and hours logging is enabled.',
  true,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{
    "sla_hours": 24,
    "set_placement_status": "active",
    "enable_hours_logging": true,
    "start_monitoring_clock": true,
    "notify_on_complete": ["trainer", "admin", "student", "supervisor"]
  }'::jsonb
),

-- Phase 12: Monitoring
(
  '00000000-0000-0000-0000-000000000010', 12, 'monitoring',
  'Ongoing Monitoring',
  'Conduct scheduled monitoring contacts with student and/or supervisor throughout placement. '
  'Minimum one contact per four-week period; more frequent for at-risk placements. '
  'Document each contact, progress ratings, and any issues or actions required.',
  true,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{
    "contact_frequency_weeks": 4,
    "at_risk_frequency_weeks": 2,
    "minimum_visits_required": 1,
    "auto_flag_if_overdue": true,
    "concurrent_with_phases": ["evidence_collection"],
    "notify_on_complete": ["trainer"]
  }'::jsonb
),

-- Phase 13: Evidence Collection
(
  '00000000-0000-0000-0000-000000000010', 13, 'evidence_collection',
  'Evidence Collection',
  'Student collects and uploads evidence of competency throughout the placement. '
  'Evidence must address all units in CHC33021 with placement components. '
  'Trainer reviews and approves evidence items; supervisor provides competency sign-offs.',
  true,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{
    "concurrent_with_phases": ["monitoring"],
    "required_unit_codes": [
      "CHCCCS031", "CHCCCS038", "CHCCCS040", "CHCCCS041",
      "CHCCOM005", "CHCDIV001", "CHCLEG001", "CHCWHS001"
    ],
    "notify_on_complete": ["trainer"]
  }'::jsonb
),

-- Phase 14: Completion Sign-off
(
  '00000000-0000-0000-0000-000000000010', 14, 'completion_signoff',
  'Final Sign-Off',
  'Verify all 120 hours are completed and supervisor-verified. Confirm all competency '
  'elements are signed off. Complete final trainer review. Issue completion documentation. '
  'Placement status transitions to "completed".',
  true,
  '[{"form_code": "LR0353", "label": "Completed Placement Record Book", "is_mandatory": true}]'::jsonb,
  '[
    {"signer_role": "trainer", "label": "Final Trainer Sign-off"},
    {"signer_role": "supervisor", "label": "Supervisor Final Confirmation"}
  ]'::jsonb,
  '["LR0353"]'::jsonb,
  '{
    "sla_hours": 48,
    "require_all_hours_verified": true,
    "require_all_competencies_signed": true,
    "minimum_hours_required": 120,
    "set_placement_status": "completed",
    "notify_on_complete": ["trainer", "admin", "student", "supervisor"]
  }'::jsonb
),

-- Phase 15: Feedback
(
  '00000000-0000-0000-0000-000000000010', 15, 'feedback',
  'Feedback & CI',
  'Collect post-placement feedback from all parties for Continuous Improvement. '
  'Student survey, supervisor survey, and trainer review must all be completed. '
  'Aggregated results feed into RTO CI reporting for ASQA.',
  false,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{
    "sla_hours": 168,
    "surveys_required": ["student_post_placement", "supervisor_post_placement", "trainer_review"],
    "notify_all_parties": true,
    "feeds_ci_report": true,
    "notify_on_complete": ["admin"]
  }'::jsonb
),

-- Phase 16: Records Retention
(
  '00000000-0000-0000-0000-000000000010', 16, 'records_retention',
  'Records & Retention',
  'Archive all placement records in compliance with ASQA retention requirements. '
  'Minimum 5-year retention for placement documentation under Standards for RTOs 2015. '
  'Generate archival confirmation and update document status to "archived".',
  true,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '{
    "retention_years": 5,
    "auto_archive_documents": true,
    "generate_archive_receipt": true,
    "notify_on_complete": ["admin"]
  }'::jsonb
);

-- ---------------------------------------------------------------------------
-- Workflow Transitions (sequential flow between all 16 phases)
-- ---------------------------------------------------------------------------
INSERT INTO workflow_transitions
  (workflow_definition_id, from_step_key, to_step_key, condition_type, condition_config)
VALUES
  ('00000000-0000-0000-0000-000000000010', 'host_establishment',    'host_suitability_check',  'manual',      '{"label": "Proceed to suitability check"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'host_suitability_check','insurance_verification',  'conditional', '{"require": "host_approved"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'insurance_verification','workplace_agreement',     'conditional', '{"require": "insurance_verified"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'workplace_agreement',   'supervisor_assignment',   'conditional', '{"require": "agreement_fully_signed"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'supervisor_assignment', 'supervisor_verification', 'manual',      '{"label": "Proceed to supervisor verification"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'supervisor_verification','supervisor_briefing',    'conditional', '{"require": "supervisor_verified"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'supervisor_briefing',   'learner_readiness',       'conditional', '{"require": "briefing_acknowledged"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'learner_readiness',     'learner_info_pack',       'conditional', '{"require": "readiness_approved"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'learner_info_pack',     'tripartite_agreement',    'conditional', '{"require": "learner_pack_acknowledged"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'tripartite_agreement',  'placement_commencement',  'conditional', '{"require": "tripartite_fully_signed"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'placement_commencement','monitoring',              'auto',        '{"trigger": "on_complete"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'placement_commencement','evidence_collection',     'auto',        '{"trigger": "on_complete"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'monitoring',            'completion_signoff',      'conditional', '{"require": "hours_complete"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'evidence_collection',   'completion_signoff',      'conditional', '{"require": "evidence_reviewed"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'completion_signoff',    'feedback',                'auto',        '{"trigger": "on_complete"}'::jsonb),
  ('00000000-0000-0000-0000-000000000010', 'feedback',              'records_retention',       'auto',        '{"trigger": "on_complete"}'::jsonb);

-- =============================================================================
-- PART 5: NOTIFICATION TEMPLATES
-- Global defaults (tenant_id = NULL) — tenants can override these
-- =============================================================================

INSERT INTO notification_templates
  (tenant_id, template_key, notification_type, subject, body_html, body_text, variables)
VALUES

-- placement_created
(NULL, 'placement_created', 'placement_created',
 'New Placement Created — {{student_name}} at {{facility_name}}',
 '<p>Hello {{recipient_name}},</p>
  <p>A new work placement has been created for <strong>{{student_name}}</strong> at <strong>{{facility_name}}</strong>.</p>
  <p>Placement Reference: <strong>{{placement_reference}}</strong><br>
     Course: {{course_code}} — {{course_name}}<br>
     Planned Start: {{planned_start_date}}<br>
     Assigned Trainer: {{trainer_name}}</p>
  <p><a href="{{action_url}}">View Placement</a></p>',
 'Hello {{recipient_name}}, A new placement ({{placement_reference}}) has been created for {{student_name}} at {{facility_name}}. View: {{action_url}}',
 '[
   {"name": "student_name", "description": "Full name of the student", "required": true, "example": "Jane Smith"},
   {"name": "facility_name", "description": "Name of the host facility", "required": true, "example": "Sunnydale Aged Care"},
   {"name": "placement_reference", "description": "Unique placement reference number", "required": true, "example": "PL-2024-00123"},
   {"name": "course_code", "description": "Training package qualification code", "required": true, "example": "CHC33021"},
   {"name": "course_name", "description": "Full qualification name", "required": true, "example": "Certificate III in Individual Support"},
   {"name": "planned_start_date", "description": "Planned start date", "required": false, "example": "15/02/2024"},
   {"name": "trainer_name", "description": "Assigned trainer full name", "required": false, "example": "John Trainer"},
   {"name": "action_url", "description": "Link to the placement", "required": true, "example": "https://app.eduk8u.com/placements/xxx"},
   {"name": "recipient_name", "description": "Name of the notification recipient", "required": true, "example": "John"}
 ]'::jsonb),

-- placement_at_risk
(NULL, 'placement_at_risk', 'placement_at_risk',
 'ALERT: Placement At Risk — {{student_name}} ({{placement_reference}})',
 '<p>Hello {{recipient_name}},</p>
  <p>The placement for <strong>{{student_name}}</strong> has been flagged as <strong style="color:red;">AT RISK</strong>.</p>
  <p><strong>Risk Level:</strong> {{risk_level}}<br>
     <strong>Reason:</strong> {{risk_reason}}<br>
     <strong>Placement:</strong> {{placement_reference}}<br>
     <strong>Host Facility:</strong> {{facility_name}}</p>
  <p>Immediate action may be required. Please review the placement and resolve any outstanding issues.</p>
  <p><a href="{{action_url}}">Review Placement →</a></p>',
 'ALERT: Placement {{placement_reference}} for {{student_name}} is AT RISK ({{risk_level}}). Reason: {{risk_reason}}. Review: {{action_url}}',
 '[
   {"name": "student_name", "description": "Full name of the student", "required": true, "example": "Jane Smith"},
   {"name": "placement_reference", "description": "Unique placement reference", "required": true, "example": "PL-2024-00123"},
   {"name": "risk_level", "description": "Risk severity level", "required": true, "example": "high"},
   {"name": "risk_reason", "description": "Description of the risk", "required": true, "example": "Hours 30% below target at week 8"},
   {"name": "facility_name", "description": "Host facility name", "required": true, "example": "Sunnydale Aged Care"},
   {"name": "action_url", "description": "Link to the placement", "required": true, "example": "https://app.eduk8u.com/placements/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- placement_completed
(NULL, 'placement_completed', 'placement_completed',
 'Placement Completed — {{student_name}} — {{course_code}}',
 '<p>Hello {{recipient_name}},</p>
  <p>Congratulations! The placement for <strong>{{student_name}}</strong> has been successfully completed.</p>
  <p><strong>Hours Completed:</strong> {{hours_completed}} of {{hours_required}} required<br>
     <strong>Host Facility:</strong> {{facility_name}}<br>
     <strong>Completed:</strong> {{completion_date}}</p>
  <p><a href="{{action_url}}">View Placement Record</a></p>',
 'Placement completed for {{student_name}}. {{hours_completed}}/{{hours_required}} hours. View: {{action_url}}',
 '[
   {"name": "student_name", "description": "Student full name", "required": true, "example": "Jane Smith"},
   {"name": "hours_completed", "description": "Total hours completed", "required": true, "example": "122.5"},
   {"name": "hours_required", "description": "Required hours", "required": true, "example": "120"},
   {"name": "facility_name", "description": "Host facility name", "required": true, "example": "Sunnydale Aged Care"},
   {"name": "course_code", "description": "Course code", "required": true, "example": "CHC33021"},
   {"name": "completion_date", "description": "Date placement was completed", "required": true, "example": "30/04/2024"},
   {"name": "action_url", "description": "Link to placement", "required": true, "example": "https://app.eduk8u.com/placements/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- hours_submitted
(NULL, 'hours_submitted', 'hours_submitted',
 'Hours Submitted for Verification — {{student_name}} ({{log_date}})',
 '<p>Hello {{recipient_name}},</p>
  <p><strong>{{student_name}}</strong> has submitted placement hours for your verification.</p>
  <p><strong>Date:</strong> {{log_date}}<br>
     <strong>Hours Claimed:</strong> {{hours_claimed}}<br>
     <strong>Activities:</strong> {{activities_description}}</p>
  <p>Please review and verify or reject this entry.</p>
  <p><a href="{{action_url}}">Verify Hours →</a></p>',
 '{{student_name}} submitted {{hours_claimed}} hours for {{log_date}}. Verify: {{action_url}}',
 '[
   {"name": "student_name", "description": "Student name", "required": true, "example": "Jane Smith"},
   {"name": "log_date", "description": "Date of the hour log", "required": true, "example": "15/02/2024"},
   {"name": "hours_claimed", "description": "Hours claimed", "required": true, "example": "7.5"},
   {"name": "activities_description", "description": "Brief activities description", "required": false, "example": "Personal care support"},
   {"name": "action_url", "description": "Link to hour log", "required": true, "example": "https://app.eduk8u.com/hours/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- hours_verified
(NULL, 'hours_verified', 'hours_verified',
 'Hours Verified — {{log_date}}',
 '<p>Hello {{recipient_name}},</p>
  <p>Your placement hours for <strong>{{log_date}}</strong> have been <strong style="color:green;">verified</strong>.</p>
  <p><strong>Hours:</strong> {{hours_claimed}}<br>
     <strong>Verified by:</strong> {{verified_by}}<br>
     <strong>Total Verified:</strong> {{total_verified_hours}} of {{hours_required}} required</p>
  <p><a href="{{action_url}}">View Placement Progress</a></p>',
 'Your hours for {{log_date}} ({{hours_claimed}} hrs) have been verified. Total: {{total_verified_hours}}/{{hours_required}} hrs.',
 '[
   {"name": "log_date", "description": "Date of the verified log", "required": true, "example": "15/02/2024"},
   {"name": "hours_claimed", "description": "Hours verified", "required": true, "example": "7.5"},
   {"name": "verified_by", "description": "Name of verifier", "required": true, "example": "John Supervisor"},
   {"name": "total_verified_hours", "description": "Running total verified hours", "required": true, "example": "45.0"},
   {"name": "hours_required", "description": "Required hours", "required": true, "example": "120"},
   {"name": "action_url", "description": "Link to placement", "required": true, "example": "https://app.eduk8u.com/placements/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "Jane"}
 ]'::jsonb),

-- hours_rejected
(NULL, 'hours_rejected', 'hours_rejected',
 'Hours Rejected — {{log_date}} — Action Required',
 '<p>Hello {{recipient_name}},</p>
  <p>Your placement hours for <strong>{{log_date}}</strong> have been <strong style="color:red;">rejected</strong>.</p>
  <p><strong>Reason:</strong> {{rejection_reason}}<br>
     <strong>Rejected by:</strong> {{rejected_by}}</p>
  <p>Please review the feedback and resubmit your hours entry.</p>
  <p><a href="{{action_url}}">Resubmit Hours →</a></p>',
 'Your hours for {{log_date}} were rejected. Reason: {{rejection_reason}}. Resubmit: {{action_url}}',
 '[
   {"name": "log_date", "description": "Date of the rejected log", "required": true, "example": "15/02/2024"},
   {"name": "rejection_reason", "description": "Reason for rejection", "required": true, "example": "Time in/out not matching activities"},
   {"name": "rejected_by", "description": "Name of rejector", "required": true, "example": "John Supervisor"},
   {"name": "action_url", "description": "Link to the hours entry", "required": true, "example": "https://app.eduk8u.com/hours/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "Jane"}
 ]'::jsonb),

-- document_requires_signature
(NULL, 'document_requires_signature', 'document_requires_signature',
 'Signature Required: {{document_name}}',
 '<p>Hello {{recipient_name}},</p>
  <p>Your signature is required on the following document:</p>
  <p><strong>{{document_name}}</strong> ({{form_code}})<br>
     <strong>Related to:</strong> {{entity_description}}<br>
     <strong>Due by:</strong> {{due_date}}</p>
  <p>Please sign this document as soon as possible to avoid delays.</p>
  <p><a href="{{action_url}}">Sign Document →</a></p>',
 'Signature required on {{document_name}} ({{form_code}}) by {{due_date}}. Sign: {{action_url}}',
 '[
   {"name": "document_name", "description": "Document title", "required": true, "example": "Tripartite Placement Agreement"},
   {"name": "form_code", "description": "Form code", "required": true, "example": "CA0355"},
   {"name": "entity_description", "description": "What the document relates to", "required": false, "example": "Placement PL-2024-00123"},
   {"name": "due_date", "description": "Signature due date", "required": false, "example": "20/02/2024"},
   {"name": "action_url", "description": "Link to sign document", "required": true, "example": "https://app.eduk8u.com/sign/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "Jane"}
 ]'::jsonb),

-- document_signed
(NULL, 'document_signed', 'document_signed',
 'Document Signed: {{document_name}}',
 '<p>Hello {{recipient_name}},</p>
  <p><strong>{{document_name}}</strong> has been signed by <strong>{{signer_name}}</strong>.</p>
  <p><strong>Signed:</strong> {{signed_at}}<br>
     <strong>Signatures collected:</strong> {{signature_count}} of {{required_signature_count}}</p>
  {{#if fully_signed}}<p style="color:green;"><strong>✓ Document is now fully signed.</strong></p>{{/if}}
  <p><a href="{{action_url}}">View Document</a></p>',
 '{{document_name}} signed by {{signer_name}} ({{signature_count}}/{{required_signature_count}} signatures).',
 '[
   {"name": "document_name", "description": "Document title", "required": true, "example": "Tripartite Placement Agreement"},
   {"name": "signer_name", "description": "Name of the person who signed", "required": true, "example": "Jane Smith"},
   {"name": "signed_at", "description": "Timestamp of signing", "required": true, "example": "15/02/2024 14:30"},
   {"name": "signature_count", "description": "Number of signatures collected", "required": true, "example": "2"},
   {"name": "required_signature_count", "description": "Total signatures required", "required": true, "example": "3"},
   {"name": "fully_signed", "description": "Whether all signatures are collected", "required": false, "example": "true"},
   {"name": "action_url", "description": "Link to document", "required": true, "example": "https://app.eduk8u.com/documents/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- risk_flag_raised
(NULL, 'risk_flag_raised', 'risk_flag_raised',
 'Risk Flag Raised: {{flag_title}} — {{placement_reference}}',
 '<p>Hello {{recipient_name}},</p>
  <p>A <strong style="color:{{severity_color}};">{{severity}} risk flag</strong> has been raised against placement <strong>{{placement_reference}}</strong>.</p>
  <p><strong>Flag:</strong> {{flag_title}}<br>
     <strong>Description:</strong> {{flag_description}}<br>
     <strong>Student:</strong> {{student_name}}<br>
     <strong>Raised:</strong> {{raised_at}}</p>
  <p>Please review and take appropriate action.</p>
  <p><a href="{{action_url}}">Review Placement →</a></p>',
 'RISK FLAG ({{severity}}): {{flag_title}} on placement {{placement_reference}} for {{student_name}}. Review: {{action_url}}',
 '[
   {"name": "flag_title", "description": "Risk flag title", "required": true, "example": "Hours significantly behind schedule"},
   {"name": "flag_description", "description": "Detailed flag description", "required": true, "example": "Student has completed only 30 of 120 required hours with 4 weeks remaining"},
   {"name": "severity", "description": "Risk severity level", "required": true, "example": "high"},
   {"name": "severity_color", "description": "Color for severity display", "required": false, "example": "red"},
   {"name": "placement_reference", "description": "Placement reference", "required": true, "example": "PL-2024-00123"},
   {"name": "student_name", "description": "Student name", "required": true, "example": "Jane Smith"},
   {"name": "raised_at", "description": "When the flag was raised", "required": true, "example": "15/02/2024 09:15"},
   {"name": "action_url", "description": "Link to placement", "required": true, "example": "https://app.eduk8u.com/placements/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- compliance_alert
(NULL, 'compliance_alert', 'compliance_alert',
 'Compliance Alert — {{alert_type}} — {{placement_reference}}',
 '<p>Hello {{recipient_name}},</p>
  <p>A compliance alert requires your attention for placement <strong>{{placement_reference}}</strong>.</p>
  <p><strong>Alert Type:</strong> {{alert_type}}<br>
     <strong>Details:</strong> {{alert_details}}<br>
     <strong>Compliance Score:</strong> {{compliance_score}}%<br>
     <strong>Student:</strong> {{student_name}}</p>
  <p><a href="{{action_url}}">Review Compliance →</a></p>',
 'Compliance Alert ({{alert_type}}) on {{placement_reference}} for {{student_name}}. Score: {{compliance_score}}%. Review: {{action_url}}',
 '[
   {"name": "alert_type", "description": "Type of compliance alert", "required": true, "example": "Missing supervisor verification"},
   {"name": "alert_details", "description": "Alert details", "required": true, "example": "CA0395 not completed; placement cannot commence"},
   {"name": "compliance_score", "description": "Current compliance score", "required": true, "example": "45"},
   {"name": "placement_reference", "description": "Placement reference", "required": true, "example": "PL-2024-00123"},
   {"name": "student_name", "description": "Student name", "required": true, "example": "Jane Smith"},
   {"name": "action_url", "description": "Link to compliance dashboard", "required": true, "example": "https://app.eduk8u.com/compliance/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- monitoring_visit_due
(NULL, 'monitoring_visit_due', 'monitoring_visit_due',
 'Monitoring Visit Due — {{student_name}} — {{placement_reference}}',
 '<p>Hello {{recipient_name}},</p>
  <p>A monitoring contact is due for <strong>{{student_name}}</strong>''s placement.</p>
  <p><strong>Placement:</strong> {{placement_reference}}<br>
     <strong>Last Contact:</strong> {{last_contact_date}}<br>
     <strong>Due By:</strong> {{due_date}}<br>
     <strong>Host Facility:</strong> {{facility_name}}</p>
  <p>Please conduct a monitoring contact and record the outcome.</p>
  <p><a href="{{action_url}}">Record Monitoring Visit →</a></p>',
 'Monitoring visit due for {{student_name}} ({{placement_reference}}) by {{due_date}}. Record: {{action_url}}',
 '[
   {"name": "student_name", "description": "Student name", "required": true, "example": "Jane Smith"},
   {"name": "placement_reference", "description": "Placement reference", "required": true, "example": "PL-2024-00123"},
   {"name": "last_contact_date", "description": "Date of last monitoring contact", "required": false, "example": "01/02/2024"},
   {"name": "due_date", "description": "Date by which visit must occur", "required": true, "example": "29/02/2024"},
   {"name": "facility_name", "description": "Host facility name", "required": true, "example": "Sunnydale Aged Care"},
   {"name": "action_url", "description": "Link to record visit", "required": true, "example": "https://app.eduk8u.com/monitoring/new"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- audit_reminder
(NULL, 'audit_reminder', 'audit_reminder',
 'Audit Readiness Reminder — {{count}} Placements Need Attention',
 '<p>Hello {{recipient_name}},</p>
  <p>Your ASQA audit readiness check has identified <strong>{{count}} placements</strong> requiring attention.</p>
  <p><strong>Average Compliance Score:</strong> {{avg_score}}%<br>
     <strong>Critical Issues:</strong> {{critical_count}}<br>
     <strong>Missing Documents:</strong> {{missing_docs_count}}<br>
     <strong>Missing Signatures:</strong> {{missing_sigs_count}}</p>
  <p><a href="{{action_url}}">View Compliance Dashboard →</a></p>',
 '{{count}} placements need attention. Avg score: {{avg_score}}%. Review: {{action_url}}',
 '[
   {"name": "count", "description": "Number of placements needing attention", "required": true, "example": "5"},
   {"name": "avg_score", "description": "Average compliance score", "required": true, "example": "72"},
   {"name": "critical_count", "description": "Number of critical issues", "required": true, "example": "2"},
   {"name": "missing_docs_count", "description": "Count of missing documents", "required": true, "example": "8"},
   {"name": "missing_sigs_count", "description": "Count of missing signatures", "required": true, "example": "4"},
   {"name": "action_url", "description": "Link to compliance dashboard", "required": true, "example": "https://app.eduk8u.com/compliance"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- host_approval_required
(NULL, 'host_approval_required', 'host_approval_required',
 'Host Facility Approval Required — {{facility_name}}',
 '<p>Hello {{recipient_name}},</p>
  <p>A new host facility requires your approval before placements can proceed.</p>
  <p><strong>Facility:</strong> {{facility_name}}<br>
     <strong>ABN:</strong> {{abn}}<br>
     <strong>Submitted by:</strong> {{submitted_by}}<br>
     <strong>Suitability Score:</strong> {{suitability_score}}/5</p>
  <p><a href="{{action_url}}">Review & Approve →</a></p>',
 'Host facility approval required: {{facility_name}}. Review: {{action_url}}',
 '[
   {"name": "facility_name", "description": "Facility name", "required": true, "example": "Sunnydale Aged Care"},
   {"name": "abn", "description": "ABN of the facility", "required": false, "example": "12 345 678 901"},
   {"name": "submitted_by", "description": "Who submitted the facility", "required": true, "example": "John Trainer"},
   {"name": "suitability_score", "description": "Overall suitability score", "required": false, "example": "4"},
   {"name": "action_url", "description": "Link to approval page", "required": true, "example": "https://app.eduk8u.com/facilities/xxx/approve"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "Admin"}
 ]'::jsonb),

-- supervisor_verification_required
(NULL, 'supervisor_verification_required', 'supervisor_verification_required',
 'Supervisor Verification Required — {{supervisor_name}}',
 '<p>Hello {{recipient_name}},</p>
  <p>A supervisor requires qualification verification (CA0395) before the placement can proceed.</p>
  <p><strong>Supervisor:</strong> {{supervisor_name}}<br>
     <strong>Facility:</strong> {{facility_name}}<br>
     <strong>Position:</strong> {{position_title}}<br>
     <strong>Related Placement:</strong> {{placement_reference}}</p>
  <p><a href="{{action_url}}">Verify Supervisor →</a></p>',
 'Supervisor verification needed: {{supervisor_name}} at {{facility_name}}. Verify: {{action_url}}',
 '[
   {"name": "supervisor_name", "description": "Supervisor full name", "required": true, "example": "Jane Supervisor"},
   {"name": "facility_name", "description": "Host facility name", "required": true, "example": "Sunnydale Aged Care"},
   {"name": "position_title", "description": "Supervisor''s position", "required": false, "example": "Registered Nurse"},
   {"name": "placement_reference", "description": "Placement reference", "required": false, "example": "PL-2024-00123"},
   {"name": "action_url", "description": "Link to supervisor verification", "required": true, "example": "https://app.eduk8u.com/supervisors/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- placement_overdue
(NULL, 'placement_overdue', 'placement_overdue',
 'OVERDUE: Placement Behind Schedule — {{student_name}} ({{placement_reference}})',
 '<p>Hello {{recipient_name}},</p>
  <p><strong style="color:red;">OVERDUE:</strong> The placement for <strong>{{student_name}}</strong> is behind schedule.</p>
  <p><strong>Hours Completed:</strong> {{hours_completed}} of {{hours_required}} required<br>
     <strong>Hours Remaining:</strong> {{hours_remaining}}<br>
     <strong>Days Until End Date:</strong> {{days_remaining}}<br>
     <strong>Required Daily Rate:</strong> {{required_daily_hours}} hrs/day to complete on time</p>
  <p>Immediate intervention may be required.</p>
  <p><a href="{{action_url}}">Review Placement →</a></p>',
 'OVERDUE: {{student_name}} placement {{placement_reference}} — {{hours_completed}}/{{hours_required}} hrs with {{days_remaining}} days left.',
 '[
   {"name": "student_name", "description": "Student name", "required": true, "example": "Jane Smith"},
   {"name": "placement_reference", "description": "Placement reference", "required": true, "example": "PL-2024-00123"},
   {"name": "hours_completed", "description": "Hours completed", "required": true, "example": "45"},
   {"name": "hours_required", "description": "Required hours", "required": true, "example": "120"},
   {"name": "hours_remaining", "description": "Hours still to complete", "required": true, "example": "75"},
   {"name": "days_remaining", "description": "Days until planned end", "required": true, "example": "14"},
   {"name": "required_daily_hours", "description": "Daily hours needed to complete on time", "required": true, "example": "5.4"},
   {"name": "action_url", "description": "Link to placement", "required": true, "example": "https://app.eduk8u.com/placements/xxx"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- system_alert
(NULL, 'system_alert', 'system_alert',
 'System Alert — {{alert_title}}',
 '<p>Hello {{recipient_name}},</p>
  <p><strong>System Alert:</strong> {{alert_title}}</p>
  <p>{{alert_message}}</p>
  {{#if action_url}}<p><a href="{{action_url}}">Take Action →</a></p>{{/if}}',
 'System Alert: {{alert_title}}. {{alert_message}}',
 '[
   {"name": "alert_title", "description": "Alert title", "required": true, "example": "Scheduled maintenance"},
   {"name": "alert_message", "description": "Alert body", "required": true, "example": "The system will be unavailable from 2am–4am AEST"},
   {"name": "action_url", "description": "Optional action link", "required": false, "example": "https://status.eduk8u.com"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "John"}
 ]'::jsonb),

-- general
(NULL, 'general', 'general',
 '{{title}}',
 '<p>Hello {{recipient_name}},</p>
  <p>{{message}}</p>
  {{#if action_url}}<p><a href="{{action_url}}">View Details →</a></p>{{/if}}',
 '{{message}}',
 '[
   {"name": "title", "description": "Notification title", "required": true, "example": "Your account has been updated"},
   {"name": "message", "description": "Notification body", "required": true, "example": "Your profile details have been updated successfully."},
   {"name": "action_url", "description": "Optional action link", "required": false, "example": "https://app.eduk8u.com/profile"},
   {"name": "recipient_name", "description": "Recipient name", "required": true, "example": "Jane"}
 ]'::jsonb);

-- =============================================================================
-- PART 6: DEMO SUBSCRIPTION FOR ICQA
-- =============================================================================

INSERT INTO subscriptions (
  tenant_id,
  plan_name,
  status,
  billing_cycle,
  amount,
  currency,
  max_students,
  max_placements,
  current_period_start,
  current_period_end
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  'enterprise',
  'active',
  'annual',
  9900.00,
  'AUD',
  NULL,
  NULL,
  NOW(),
  NOW() + INTERVAL '1 year'
);

-- =============================================================================
-- END OF MIGRATION 012
-- =============================================================================
